version: '3.8'

services:
  api-gateway:
    container_name: connectfy-api-gateway-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - connectfy-core-network
      - connectfy-kafka-network
      - connectfy-redis-network
    env_file:
      - .env.development

networks:
  connectfy-core-network:
    external: true
  connectfy-kafka-network:
    external: true
  connectfy-redis-network:
    external: true