version: '3.8'

services:
  api-gateway:
    container_name: api-gateway-dev
    image: connectfy/api-gateway-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - api-gateway-network
      - kafka_network
      - auth-network
      # - main-network
      # - permissions-network
      # - fileuploader-network
    environment:
      - NODE_ENV=development
    command: npm run start:dev
    restart: unless-stopped
    env_file:
      - .env.development

networks:
  api-gateway-network:
    external: true
  kafka_network:
    external: true
  auth-network:
    external: true
  # main-network:
  #   external: true
  # permissions-network:
  #   external: true
  # fileuploader-network:
  #   external: true
