version: '3.8'

services:
  api-gateway:
    container_name: connectfy-api-gateway-prod
    image: connectfy/connectfy-api-gateway-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    networks:
      - connectfy-api-gateway-network
      - connectfy-kafka-network
      - connectfy-auth-network
      # - main-network
      # - permissions-network
      # - fileuploader-network
    environment:
      - NODE_ENV=production
    restart: always
    env_file:
      - .env.production

networks:
  connectfy-api-gateway-network:
    external: true
  connectfy-kafka-network:
    external: true
  connectfy-auth-network:
    external: true
  # main-network:
  #   external: true
  # permissions-network:
  #   external: true
  # fileuploader-network:
  #   external: true
